<a href="https://colab.research.google.com/github/SangamSilwal/Machine-learning-Series/blob/main/K_Mean_Cluster_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import random
import numpy as np

In [56]:
class KMeans:
  def __init__(self,n_clusters=2,max_iter=100):
    self.n_clusters = n_clusters
    self.max_iter = max_iter
    self.centroids = None

  def fit_predict(self,X):

    random_index = random.sample(range(0,X.shape[0]),self.n_clusters)
    self.centroids = X[random_index]
    print(self.centroids)

    for i in range(self.max_iter):
        cluster_group = self.assign_clusters(X)
        old_centroids = self.centroids
        self.centroids = self.move_centroids(X,cluster_group)
        if (old_centroids == self.centroids).all():
          break
    return cluster_group


  def assign_clusters(self,X):
    cluster_group = []
    distances = []
    for row in X:
      for centroid in self.centroids:
        distances.append(np.sqrt(np.dot(row-centroid,row-centroid)))
      min_distance = min(distances)
      index_pos = distances.index(min_distance)
      cluster_group.append(index_pos)
      distances.clear()

    return np.array(cluster_group)

  def move_centroids(self,X,cluster_group):
    new_centroids = []
    cluster_type = np.unique(cluster_group)
    for type in cluster_type:
      new_centroids.append(X[cluster_group==type].mean(axis=0))

    return np.array(new_centroids)


In [57]:
X = np.array([[1,2,3],[3,4,5]])
km = KMeans()
km.fit_predict(X)


[[1 2 3]
 [3 4 5]]


array([0, 1])

In [27]:
x = [[4,9,0],[4,0,6]]
min(x)


[4, 0, 6]