<a href="https://colab.research.google.com/github/SangamSilwal/Machine-learning-Series/blob/main/predicting_without_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle

In [2]:
import numpy as np

In [3]:
ohe_sex = pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl','rb'))
clf = pickle.load(open('clf.pkl','rb'))

In [51]:
test_input = np.array([2,"male",30.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [52]:
test_input[:,1].reshape(1,1)

array([['male']], dtype=object)

In [53]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [54]:
test_input_sex

array([[0., 1.]])

In [55]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [56]:
test_input_embarked

array([[0., 0., 1.]])

In [57]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_age

array([[30.0]], dtype=object)

In [58]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [59]:
test_input_transformed.shape

(1, 10)

In [60]:
clf.predict(test_input_transformed)

array([0])